project:
  type: default
  output-dir: docs
  render:
    - index.qmd
    - introduction-to-sql.qmd
    - introduction-to-bigquery.qmd

format:
  html:
    toc: true
    toc-title: Contents
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    embed-resources: true
    code-copy: true
